export const PHONE_CASE_BRANDS: Record<string, string[]> = {
    Apple: [
        "iPhone 6",
        "iPhone 6 (Logo Cut)",
        "iPhone 6 Plus",
        "iPhone 6S",
        "iPhone 6S (Logo Cut)",
        "iPhone 6S Plus",
        "iPhone 7",
        "iPhone 7 (Logo Cut)",
        "iPhone 7 Plus",
        "iPhone 7 Plus (Logo Cut)",
        "iPhone 8",
        "iPhone 8 Plus",
        "iPhone SE (2020)",
        "iPhone X",
        "iPhone X (Logo Cut)",
        "iPhone XR",
        "iPhone XS",
        "iPhone XS Max",
        "iPhone XS Max (Logo Cut)",
        "iPhone 11",
        "iPhone 11 Pro",
        "iPhone 11 Pro Max",
        "iPhone 12",
        "iPhone 12 Mini",
        "iPhone 12 Pro",
        "iPhone 12 Pro Max",
        "iPhone 13",
        "iPhone 13 Mini",
        "iPhone 13 Pro",
        "iPhone 13 Pro Max",
        "iPhone 14",
        "iPhone 14 Plus",
        "iPhone 14 Pro",
        "iPhone 14 Pro Max",
        "iPhone 15",
        "iPhone 15 Plus",
        "iPhone 15 Pro",
        "iPhone 15 Pro Max",
        "iPhone 16",
        "iPhone 16 Plus",
        "iPhone 16 Pro",
        "iPhone 16 Pro Max",
        "iPhone 16E",
        "iPhone 17",
        "iPhone 17 Air",
        "iPhone 17 Pro",
        "iPhone 17 Pro Max",
        "iPhone 17E",
    ],
    Samsung: [
        "Galaxy A02S",
        "Galaxy A03",
        "Galaxy A03 Core",
        "Galaxy A03S",
        "Galaxy A04",
        "Galaxy A04E",
        "Galaxy A04S",
        "Galaxy A05",
        "Galaxy A05S",
        "Galaxy A06 (4G)",
        "Galaxy A06 (5G)",
        "Galaxy A07 (4G)",
        "Galaxy A07 (5G)",
        "Galaxy A10",
        "Galaxy A10S",
        "Galaxy A12",
        "Galaxy A13",
        "Galaxy A14 (5G)",
        "Galaxy A15 (5G)",
        "Galaxy A16 (5G)",
        "Galaxy A17 (5G)",
        "Galaxy A20",
        "Galaxy A20S",
        "Galaxy A21S",
        "Galaxy A22 (4G)",
        "Galaxy A22 (5G)",
        "Galaxy A23",
        "Galaxy A25 (5G)",
        "Galaxy A26 (5G)",
        "Galaxy A27 (5G)",
        "Galaxy A30",
        "Galaxy A30S",
        "Galaxy A31",
        "Galaxy A32 (4G)",
        "Galaxy A33 (5G)",
        "Galaxy A34 (5G)",
        "Galaxy A35 (5G)",
        "Galaxy A36 (5G)",
        "Galaxy A37 (5G)",
        "Galaxy A5 (2018)",
        "Galaxy A50",
        "Galaxy A50S",
        "Galaxy A51",
        "Galaxy A52 (5G)",
        "Galaxy A52S (5G)",
        "Galaxy A53 (5G)",
        "Galaxy A54 (5G)",
        "Galaxy A55 (5G)",
        "Galaxy A56 (5G)",
        "Galaxy A57 (5G)",
        "Galaxy A6 Plus",
        "Galaxy A7 (2018)",
        "Galaxy A70",
        "Galaxy A70S",
        "Galaxy A71",
        "Galaxy A72",
        "Galaxy A73 (5G)",
        "Galaxy A9 (2018)",
        "Galaxy A9 Pro",

        "Galaxy C9",
        "Galaxy C9 Pro",

        "Galaxy F02S",
        "Galaxy F04",
        "Galaxy F05",
        "Galaxy F06",
        "Galaxy F12",
        "Galaxy F13",
        "Galaxy F14 (5G)",
        "Galaxy F15 (5G)",
        "Galaxy F16 (5G)",
        "Galaxy F17 (5G)",
        "Galaxy F22",
        "Galaxy F23 (5G)",
        "Galaxy F34 (5G)",
        "Galaxy F36 (5G)",
        "Galaxy F41",
        "Galaxy F42 (5G)",
        "Galaxy F54 (5G)",
        "Galaxy F55 (5G)",
        "Galaxy F62",
        "Galaxy F70E (5G)",

        "Galaxy J2 (2016)",
        "Galaxy J2 (2018)",
        "Galaxy J2 Pro (2016)",
        "Galaxy J6 (2018)",
        "Galaxy J6 Prime",
        "Galaxy J7 (2015)",
        "Galaxy J7 (2016)",
        "Galaxy J7 (2017)",
        "Galaxy J7 Duo",
        "Galaxy J7 Max",
        "Galaxy J7 Nxt",
        "Galaxy J7 Prime",
        "Galaxy J7 Prime 2",
        "Galaxy J7 Pro",
        "Galaxy J8",

        "Galaxy M01",
        "Galaxy M01 Core",
        "Galaxy M01S",
        "Galaxy M02",
        "Galaxy M02S",
        "Galaxy M04",
        "Galaxy M05",
        "Galaxy M06",
        "Galaxy M07",
        "Galaxy M10",
        "Galaxy M10S",
        "Galaxy M11",
        "Galaxy M12",
        "Galaxy M13 (4G)",
        "Galaxy M13 (5G)",
        "Galaxy M14 (5G)",
        "Galaxy M15 (5G)",
        "Galaxy M16 (5G)",
        "Galaxy M17 (5G)",
        "Galaxy M17E (5G)",
        "Galaxy M20",
        "Galaxy M21 (2021)",
        "Galaxy M21 (4G)",
        "Galaxy M30",
        "Galaxy M30S",
        "Galaxy M31",
        "Galaxy M31 Prime",
        "Galaxy M31S",
        "Galaxy M32 (4G)",
        "Galaxy M32 (5G)",
        "Galaxy M33 (5G)",
        "Galaxy M34 (5G)",
        "Galaxy M35 (5G)",
        "Galaxy M36 (5G)",
        "Galaxy M40",
        "Galaxy M42 (5G)",
        "Galaxy M51",
        "Galaxy M52 (5G)",
        "Galaxy M53 (5G)",
        "Galaxy M55 (5G)",
        "Galaxy M56 (5G)",

        "Galaxy Note 8",
        "Galaxy Note 9",
        "Galaxy Note 10",
        "Galaxy Note 10 Lite",
        "Galaxy Note 10 Plus",
        "Galaxy Note 20",
        "Galaxy Note 20 Ultra",

        "Galaxy On 6",
        "Galaxy On Nxt",
        "Galaxy On7 Pro",

        "Galaxy S8",
        "Galaxy S8 Plus",
        "Galaxy S9",
        "Galaxy S9 Plus",
        "Galaxy S10",
        "Galaxy S10 Plus",
        "Galaxy S20",
        "Galaxy S20 FE (5G)",
        "Galaxy S20 Plus",
        "Galaxy S20 Ultra",
        "Galaxy S21 (5G)",
        "Galaxy S21 FE (5G)",
        "Galaxy S21 Plus",
        "Galaxy S21 Ultra",
        "Galaxy S22 (5G)",
        "Galaxy S22 Plus",
        "Galaxy S22 Ultra",
        "Galaxy S23 (5G)",
        "Galaxy S23 FE (5G)",
        "Galaxy S23 Plus (5G)",
        "Galaxy S23 Ultra",
        "Galaxy S24 (5G)",
        "Galaxy S24 FE (5G)",
        "Galaxy S24 Plus (5G)",
        "Galaxy S24 Ultra (5G)",
        "Galaxy S25 (5G)",
        "Galaxy S25 Edge (5G)",
        "Galaxy S25 FE (5G)",
        "Galaxy S25 Plus (5G)",
        "Galaxy S25 Ultra (5G)",
        "Galaxy S26 (5G)",
        "Galaxy S26 Plus (5G)",
        "Galaxy S26 Ultra (5G)",

        "Galaxy Z Flip 3 (5G)",
        "Galaxy Z Flip 5 (5G)",
        "Galaxy Z Flip 6 (5G)",
        "Galaxy Z Flip 7 (5G)",
        "Galaxy Z Fold 4 (5G)",
        "Galaxy Z Fold 5 (5G)",
        "Galaxy Z Fold 6 (5G)",
        "Galaxy Z Fold 7 (5G)",
    ],
    OnePlus: [
        "3",
        "3T",
        "5",
        "5T",
        "6",
        "6T",
        "7",
        "7 Pro",
        "7T",
        "7T Pro",
        "8",
        "8 Pro",
        "8T (5G)",
        "9 (5G)",
        "9 Pro (5G)",
        "9R (5G)",
        "9RT (5G)",
        "10 Pro (5G)",
        "10R (5G)",
        "10T (5G)",
        "11 (5G)",
        "11R (5G)",
        "12 (5G)",
        "12R (5G)",
        "13 (5G)",
        "13R (5G)",
        "13S (5G)",
        "13T (5G)",
        "15 (5G)",
        "15R (5G)",
        "15T (5G)",
        "Nord",
        "Nord 2 (5G)",
        "Nord 2T (5G)",
        "Nord 3 (5G)",
        "Nord 4 (5G)",
        "Nord 5 (5G)",
        "Nord 6 (5G)",
        "Nord CE",
        "Nord CE 2 (5G)",
        "Nord CE 2 Lite (5G)",
        "Nord CE 3 (5G)",
        "Nord CE 3 Lite (5G)",
        "Nord CE 4 (5G)",
        "Nord CE 4 Lite (5G)",
        "Nord CE 5 (5G)",
        "Nord CE 6 (5G)",
        "Nord CE 6 Lite (5G)",
    ],
    Xiaomi: [
        "Mi A1",
        "Mi A2",
        "Mi A3",
        "Mi Max",
        "Mi Max 2",

        "Mi 10",
        "Mi 10I (5G)",
        "Mi 10T (5G)",
        "Mi 10T Pro (5G)",
        "Mi 11 Lite",
        "Mi 11 Lite NE (5G)",
        "Mi 11 Ultra",
        "Mi 11I (5G)",
        "Mi 11I HyperCharge (5G)",
        "Mi 11T Pro (5G)",
        "Mi 11X (5G)",
        "Mi 11X Pro (5G)",
        "Mi 12 Pro (5G)",
        "Mi 13 Pro (5G)",
        "Mi 14 (5G)",
        "Mi 14 Civi (5G)",
        "Mi 15 (5G)",
        "Mi 15 Ultra",
        "Mi 17 Ultra",

        "Redmi A1 (2022)",
        "Redmi A1 Plus",
        "Redmi A2",
        "Redmi A2 Plus",
        "Redmi A3 (2024)",
        "Redmi A3X",
        "Redmi A4 (5G)",
        "Redmi A5",
        "Redmi A7 Pro",

        "Redmi Go",

        "Redmi 3S",
        "Redmi 3S Prime",
        "Redmi 4A",
        "Redmi 5",
        "Redmi 5A",
        "Redmi 6",
        "Redmi 6 Pro",
        "Redmi 6A",
        "Redmi 7",
        "Redmi 7A",
        "Redmi 8",
        "Redmi 8A",
        "Redmi 8A Dual",
        "Redmi 9",
        "Redmi 9 Activ",
        "Redmi 9 Power",
        "Redmi 9 Prime",
        "Redmi 9A",
        "Redmi 9A Sport",
        "Redmi 9I",
        "Redmi 9I Sport",
        "Redmi 10",
        "Redmi 10 Power",
        "Redmi 10 Prime (2022)",
        "Redmi 10A",
        "Redmi 11 Prime (4G)",
        "Redmi 11 Prime (5G)",
        "Redmi 12 (4G)",
        "Redmi 12 (5G)",
        "Redmi 12C",
        "Redmi 13 (5G)",
        "Redmi 13C (4G)",
        "Redmi 13C (5G)",
        "Redmi 14C (5G)",
        "Redmi 15 (5G)",
        "Redmi 15A (5G)",
        "Redmi 15C (5G)",

        "Redmi K20",
        "Redmi K20 Pro",
        "Redmi K50I (5G)",

        "Redmi Note 4",
        "Redmi Note 5",
        "Redmi Note 5 Pro",
        "Redmi Note 6 Pro",
        "Redmi Note 7",
        "Redmi Note 7 Pro",
        "Redmi Note 7S",
        "Redmi Note 8",
        "Redmi Note 8 Pro",
        "Redmi Note 9",
        "Redmi Note 9 Pro",
        "Redmi Note 9 Pro Max",
        "Redmi Note 10",
        "Redmi Note 10 Lite",
        "Redmi Note 10 Pro",
        "Redmi Note 10 Pro Max",
        "Redmi Note 10S",
        "Redmi Note 10T (5G)",
        "Redmi Note 11",
        "Redmi Note 11 Pro (4G)",
        "Redmi Note 11 Pro (5G)",
        "Redmi Note 11 Pro Plus (5G)",
        "Redmi Note 11 SE",
        "Redmi Note 11S",
        "Redmi Note 11T (5G)",
        "Redmi Note 12 (4G)",
        "Redmi Note 12 (5G)",
        "Redmi Note 12 Pro (5G)",
        "Redmi Note 12 Pro Plus (5G)",
        "Redmi Note 13 (5G)",
        "Redmi Note 13 Pro (5G)",
        "Redmi Note 13 Pro Plus (5G)",
        "Redmi Note 14 (5G)",
        "Redmi Note 14 Pro (5G)",
        "Redmi Note 14 Pro Plus (5G)",
        "Redmi Note 14 SE (5G)",
        "Redmi Note 15 (5G)",
        "Redmi Note 15 Pro (5G)",
        "Redmi Note 15 Pro Plus (5G)",

        "Redmi Y1",
        "Redmi Y2",
        "Redmi Y3",
    ],
    Motorola: [
        "Edge 20 Fusion",
        "Edge 20 Pro",
        "Edge 30 Pro",
        "G8 Power Lite",
        "Moto E13",
        "Moto E32S",
        "Moto E40",
        "Moto E7 Power",
        "Moto Edge 20",
        "Moto Edge 30",
        "Moto Edge 30 Fusion",
        "Moto Edge 30 Ultra",
        "Moto Edge 40",
        "Moto Edge 40 Neo",
        "Moto Edge 5",
        "Moto Edge 50 (5G)",
        "Moto Edge 50 Fusion (5G)",
        "Moto Edge 50 Neo (5G)",
        "Moto Edge 50 Pro (5G)",
        "Moto Edge 50 Ultra (5G)",
        "Moto Edge 60 (5G)",
        "Moto Edge 60 Fusion (5G)",
        "Moto Edge 60 Pro (5G)",
        "Moto Edge 60 Stylus",
        "Moto Edge 70 (5G)",
        "Moto Edge 70 Fusion (5G)",
        "Moto Edge 70 Pro (5G)",
        "Moto G",
        "Moto G04",
        "Moto G04S",
        "Moto G05",
        "Moto G06 Power",
        "Moto G10",
        "Moto G10 Power",
        "Moto G13",
        "Moto G14",
        "Moto G17",
        "Moto G22",
        "Moto G24 Power",
        "Moto G30",
        "Moto G31",
        "Moto G32",
        "Moto G34 (5G)",
        "Moto G35 (5G)",
        "Moto G40 Fusion",
        "Moto G42",
        "Moto G45 (5G)",
        "Moto G5 Plus",
        "Moto G51 (5G)",
        "Moto G52",
        "Moto G54 (5G)",
        "Moto G57 Power (5G)",
        "Moto G5S Plus",
        "Moto G60",
        "Moto G62 (5G)",
        "Moto G64 (5G)",
        "Moto G67 Power (5G)",
        "Moto G71 (5G)",
        "Moto G72",
        "Moto G73 (5G)",
        "Moto G82 (5G)",
        "Moto G84 (5G)",
        "Moto G85 (5G)",
        "Moto G86 (5G)",
        "Moto G86 Power (5G)",
        "Moto G9",
        "Moto G9 Plus",
        "Moto G9 Power",
        "Moto G96 (5G)",
        "Moto Signature",
        "One Fusion Plus",
    ],
    Nothing: [
        "CMF Phone 1",
        "CMF Phone 2 Pro (5G)",
        "Phone 1",
        "Phone 2",
        "Phone 2A",
        "Phone 2A Plus",
        "Phone 3",
        "Phone 3A",
        "Phone 3A Lite",
        "Phone 3A Pro",
        "Phone 4A",
        "Phone 4A Pro",
        "Phone 4B",
    ],
    Realme: [
        "1",
        "2",
        "2 Pro",
        "3",
        "3 Pro",
        "3I",
        "5",
        "5 Pro",
        "5I",
        "5S",
        "6",
        "6 Pro",
        "6I",
        "6S",
        "7",
        "7 Pro",
        "7I",
        "8 (4G)",
        "8 (5G)",
        "8 Pro",
        "8I",
        "8S (5G)",
        "9 (4G)",
        "9 (5G)",
        "9 Pro (5G)",
        "9 Pro Plus (5G)",
        "9 SE (5G)",
        "9I (4G)",
        "9I (5G)",
        "10 (4G)",
        "10 Pro (5G)",
        "10 Pro Plus (5G)",
        "11 (5G)",
        "11 Pro (5G)",
        "11 Pro Plus (5G)",
        "11X (5G)",
        "12 (5G)",
        "12 Plus (5G)",
        "12 Pro (5G)",
        "12 Pro Plus (5G)",
        "12X (5G)",
        "13 (5G)",
        "13 Plus (5G)",
        "13 Pro (5G)",
        "13 Pro Plus (5G)",
        "14 (5G)",
        "14 Pro (5G)",
        "14 Pro Lite (5G)",
        "14 Pro Plus (5G)",
        "14T (5G)",
        "14X (5G)",
        "15 (5G)",
        "15 Pro (5G)",
        "15T (5G)",
        "15X (5G)",
        "16 (5G)",
        "16 Pro (5G)",
        "16 Pro Plus (5G)",
        "16T (5G)",

        "C1",
        "C2",
        "C3",
        "C11 (2020)",
        "C11 (2021)",
        "C12",
        "C15",
        "C17",
        "C20",
        "C21",
        "C21Y",
        "C25",
        "C25S",
        "C25Y",
        "C30",
        "C30S",
        "C31",
        "C33",
        "C33 (2023)",
        "C35",
        "C51",
        "C53",
        "C55",
        "C61",
        "C63 (4G)",
        "C63 (5G)",
        "C65 (5G)",
        "C67 (5G)",
        "C71 (4G)",
        "C71 (5G)",
        "C73 (5G)",
        "C75 (5G)",
        "C83 (5G)",
        "C85 (5G)",

        "GT (5G)",
        "GT 2",
        "GT 2 Pro",
        "GT 6",
        "GT 6T (5G)",
        "GT 7 (5G)",
        "GT 7 Pro (5G)",
        "GT 7T (5G)",
        "GT Master Edition",
        "GT Neo 2",
        "GT Neo 3",
        "GT Neo 3T",

        "Narzo 10",
        "Narzo 10A",
        "Narzo 20",
        "Narzo 20 Pro",
        "Narzo 20A",
        "Narzo 30 (4G)",
        "Narzo 30 (5G)",
        "Narzo 30 Pro (5G)",
        "Narzo 30A",
        "Narzo 50 (4G)",
        "Narzo 50 (5G)",
        "Narzo 50 Pro",
        "Narzo 50A",
        "Narzo 50A Prime",
        "Narzo 50I",
        "Narzo 50I Prime",
        "Narzo 60 (5G)",
        "Narzo 60 Pro (5G)",
        "Narzo 60X (5G)",
        "Narzo 70 (5G)",
        "Narzo 70 Pro (5G)",
        "Narzo 70 Turbo (5G)",
        "Narzo 70X (5G)",
        "Narzo 80 Lite (5G)",
        "Narzo 80 Pro (5G)",
        "Narzo 80X (5G)",
        "Narzo 90 (5G)",
        "Narzo 90X (5G)",
        "Narzo N53",
        "Narzo N55",
        "Narzo N63",
        "Narzo N65 (5G)",

        "P1 (5G)",
        "P1 Pro (5G)",
        "P1 Speed (5G)",
        "P2 Pro (5G)",
        "P3 (5G)",
        "P3 Pro (5G)",
        "P3 Ultra (5G)",
        "P3X (5G)",
        "P4 (5G)",
        "P4 Lite",
        "P4 Power (5G)",
        "P4 Pro (5G)",
        "P4R (5G)",
        "P4X (5G)",

        "U1",

        "X",
        "X2",
        "X2 Pro",
        "X3",
        "X3 SuperZoom",
        "X50 Pro",
        "X7 (5G)",
        "X7 Max (5G)",
        "X7 Pro (5G)",
        "XT",
    ],
    Oppo: [
        "A1K",
        "A3 (5G)",
        "A3 Pro (5G)",
        "A3S",
        "A3X (5G)",
        "A5 (2020)",
        "A5 (5G)",
        "A5 Pro (5G)",
        "A5S",
        "A5X (5G)",
        "A6 (5G)",
        "A6 Pro (5G)",
        "A6C (4G)",
        "A6C (5G)",
        "A6X (5G)",
        "A7",
        "A11K",
        "A12",
        "A15",
        "A15S",
        "A16",
        "A16E",
        "A16K",
        "A17",
        "A17K",
        "A18",
        "A31",
        "A33 (2020)",
        "A37",
        "A38",
        "A52",
        "A53",
        "A53S (5G)",
        "A54",
        "A55",
        "A57 (2016)",
        "A57 (4G)",
        "A57 (5G)",
        "A58",
        "A59 (5G)",
        "A71",
        "A71K",
        "A72",
        "A73",
        "A74 (5G)",
        "A75",
        "A75S",
        "A76",
        "A77",
        "A77S",
        "A78 (4G)",
        "A78 (5G)",
        "A79 (5G)",
        "A83",
        "A91",
        "A92",
        "A92S",
        "A96",
        "A9",
        "A9 (2020)",
        "Ace 2",
        "F3",
        "F3 Plus",
        "F5",
        "F7",
        "F7 Youth",
        "F9",
        "F9 Pro",
        "F11",
        "F11 Pro",
        "F15",
        "F17",
        "F17 Pro",
        "F19",
        "F19 Pro",
        "F19 Pro Plus",
        "F19S",
        "F21 Pro (4G)",
        "F21 Pro (5G)",
        "F21S Pro (4G)",
        "F21S Pro (5G)",
        "F23 (5G)",
        "F25 Pro (5G)",
        "F27 (5G)",
        "F27 Pro Plus (5G)",
        "F29 (5G)",
        "F29 Pro (5G)",
        "F31 (5G)",
        "F31 Pro (5G)",
        "F31 Pro Plus (5G)",
        "F33 (5G)",
        "F33 Pro (5G)",
        "Find X2 Pro",
        "Find X7",
        "Find X8",
        "Find X8 Pro",
        "Find X9",
        "Find X9 Pro",
        "Find X9 Ultra",
        "K1",
        "K3",
        "K10 (4G)",
        "K10 (5G)",
        "K12X (5G)",
        "K13 (5G)",
        "K13 Turbo (5G)",
        "K13 Turbo Pro (5G)",
        "K13X (5G)",
        "K14 (5G)",
        "R15X",
        "Reno 2",
        "Reno 2F",
        "Reno 2Z",
        "Reno 3 Pro",
        "Reno 4",
        "Reno 4 Pro",
        "Reno 5",
        "Reno 5 Pro (5G)",
        "Reno 6 (5G)",
        "Reno 6 Pro (5G)",
        "Reno 7 (4G)",
        "Reno 7 (5G)",
        "Reno 7 Pro (5G)",
        "Reno 8 (5G)",
        "Reno 8 Pro (5G)",
        "Reno 8T (5G)",
        "Reno 10 (5G)",
        "Reno 10 Pro (5G)",
        "Reno 10 Pro Plus (5G)",
        "Reno 11 (5G)",
        "Reno 11 Pro (5G)",
        "Reno 12 (5G)",
        "Reno 12 Pro (5G)",
        "Reno 13 (5G)",
        "Reno 13 Pro (5G)",
        "Reno 14 (5G)",
        "Reno 14 Pro (5G)",
        "Reno 15 (5G)",
        "Reno 15 Pro (5G)",
        "Reno 15 Pro Mini (5G)",
        "Reno 15C (5G)",
        "Reno 16 (5G)",
        "Reno 16C (5G)",
    ],
    Poco: [
        "C3",
        "C31",
        "C50",
        "C55",
        "C61",
        "C65",
        "C71 (4G)",
        "C75 (5G)",
        "C85 (5G)",
        "C85X (5G)",
        "F1",
        "F2 Pro",
        "F3 GT (5G)",
        "F4 (5G)",
        "F5 (5G)",
        "F6 (5G)",
        "F7 (5G)",
        "M2",
        "M2 Pro",
        "M2 Reloaded",
        "M3",
        "M3 Pro (5G)",
        "M4 (5G)",
        "M4 Pro (4G)",
        "M4 Pro (5G)",
        "M5",
        "M6 (5G)",
        "M6 Plus (5G)",
        "M6 Pro (5G)",
        "M7 (5G)",
        "M7 Plus (5G)",
        "M7 Pro (5G)",
        "X2",
        "X3",
        "X3 Pro",
        "X4 Pro (5G)",
        "X5 (5G)",
        "X5 Pro (5G)",
        "X6 (5G)",
        "X6 Neo (5G)",
        "X6 Pro (5G)",
        "X7 (5G)",
        "X7 Pro (5G)",
        "X8 Pro (5G)",
        "X8 Pro Max (5G)",
    ],
    Vivo: [
        "S1",
        "S1 Pro",

        "T1 (44W)",
        "T1 (5G)",
        "T1 Pro (5G)",
        "T1X",
        "T2 (5G)",
        "T2 Pro (5G)",
        "T2X (5G)",
        "T3 (5G)",
        "T3 Lite (5G)",
        "T3 Pro (5G)",
        "T3 Ultra (5G)",
        "T3X (5G)",
        "T4 (5G)",
        "T4 Lite (5G)",
        "T4 Pro (5G)",
        "T4 Ultra (5G)",
        "T4R (5G)",
        "T4X (5G)",
        "T5 Pro (5G)",
        "T5X (5G)",

        "U10",
        "U20",

        "V5",
        "V5 Lite",
        "V5 Plus",
        "V5S",
        "V7",
        "V7 Plus",
        "V9",
        "V9 Pro",
        "V9 Youth",
        "V11",
        "V11 Pro",
        "V15",
        "V15 Pro",
        "V17",
        "V17 Pro",
        "V19",
        "V20",
        "V20 Pro",
        "V20 SE",
        "V21 (5G)",
        "V21E (5G)",
        "V23 (5G)",
        "V23 Pro (5G)",
        "V23E (5G)",
        "V25 (5G)",
        "V25 Pro (5G)",
        "V27 (5G)",
        "V27 Pro (5G)",
        "V29 (5G)",
        "V29 Pro (5G)",
        "V29E (5G)",
        "V30 (5G)",
        "V30 Pro (5G)",
        "V30E (5G)",
        "V40 (5G)",
        "V40 Pro (5G)",
        "V40E (5G)",
        "V50 (5G)",
        "V50E (5G)",
        "V60 (5G)",
        "V60 Lite (5G)",
        "V60E (5G)",
        "V70 (5G)",
        "V70 Elite (5G)",
        "V70 FE (5G)",

        "X50",
        "X50 Pro",
        "X60",
        "X60 Pro",
        "X60 Pro Plus",
        "X70 Pro (5G)",
        "X70 Pro Plus",
        "X80",
        "X80 Pro",
        "X90",
        "X90 Pro",
        "X100 (5G)",
        "X100 Pro (5G)",
        "X200 (5G)",
        "X200 FE (5G)",
        "X200 Pro (5G)",
        "X200T (5G)",
        "X300 (5G)",
        "X300 FE (5G)",
        "X300 Pro (5G)",

        "Y01",
        "Y01A",
        "Y02",
        "Y02T",
        "Y05",
        "Y11",
        "Y11 (5G)",
        "Y12",
        "Y12G",
        "Y12S",
        "Y15",
        "Y15C",
        "Y15S",
        "Y16",
        "Y17",
        "Y17S",
        "Y18",
        "Y18E",
        "Y18T",
        "Y19",
        "Y19 (5G)",
        "Y19E",
        "Y19S",
        "Y19S (5G)",
        "Y1S",
        "Y20",
        "Y20A",
        "Y20G",
        "Y20I",
        "Y20T",
        "Y21",
        "Y21 (5G)",
        "Y21A",
        "Y21E",
        "Y21G",
        "Y21T",
        "Y22",
        "Y27",
        "Y28 (5G)",
        "Y28E (5G)",
        "Y28S (5G)",
        "Y29 (5G)",
        "Y30",
        "Y31 (4G)",
        "Y31 (5G)",
        "Y31 Pro (5G)",
        "Y33S",
        "Y33T",
        "Y35",
        "Y36",
        "Y38 (5G)",
        "Y39 (5G)",
        "Y50",
        "Y51",
        "Y51A",
        "Y51 Pro (5G)",
        "Y52S",
        "Y53",
        "Y53S",
        "Y56 (5G)",
        "Y58 (5G)",
        "Y65",
        "Y66",
        "Y67",
        "Y69",
        "Y71",
        "Y71I",
        "Y72 (5G)",
        "Y73",
        "Y75 (4G)",
        "Y75 (5G)",
        "Y81",
        "Y81I",
        "Y83",
        "Y83 Pro",
        "Y85",
        "Y89",
        "Y90",
        "Y91",
        "Y91I",
        "Y93",
        "Y95",
        "Y97",
        "Y100 (5G)",
        "Y100A (5G)",
        "Y200 (5G)",
        "Y200 Pro (5G)",
        "Y200E (5G)",
        "Y300 (5G)",
        "Y300 Plus (5G)",
        "Y400 (5G)",
        "Y400 Pro (5G)",

        "Z1 Pro",
        "Z1X",
    ],
};

export const PHONE_CASE_BRAND_NAMES = Object.keys(PHONE_CASE_BRANDS);

const PHONE_CASE_CATEGORY_SLUGS = [
    "mobile-covers",
    "mobile-cases",
    "phone-cases",
    "cases",
];
const PHONE_CASE_KEYWORDS = ["case", "cover", "back cover", "mobile cover"];

export function isPhoneCaseProduct(product: {
    categoryId?: string | null;
    category?: { slug?: string } | null;
    name: string;
    slug: string;
    tags?: string[];
}): boolean {
    const categorySlug = product.category?.slug;
    if (categorySlug && PHONE_CASE_CATEGORY_SLUGS.includes(categorySlug))
        return true;
    const nameLower = product.name.toLowerCase();
    if (PHONE_CASE_KEYWORDS.some((k) => nameLower.includes(k))) return true;
    const tags = product.tags ?? [];
    if (
        tags.some((t) =>
            PHONE_CASE_KEYWORDS.some((k) => t.toLowerCase().includes(k)),
        )
    )
        return true;
    return false;
}
